### ISSUE TITLE
Enchanting Table

### ISSUE THREAD

**Issue by Simax344** [firstdarkdev/pocketmachines#1]
Is there a way to increase the levels of the enchants?

**Comment by NighthowlerStudios** [comment]
This is a non issue as some other mod that removes the enchantment levels can be installed instead.  Our code just uses the exact same UI and behaviour as the regular enchantment table, so if you install a mod such as those, it will work on ours too.

**Comment by hypherionmc** [comment]
Actually something I didn't think about. Wonder if there's a way using a normal enchanting table (not sure if they sync? Do they?). If they do, then that's one way.

Otherwise I'd need to figure out a new mechanic to do this in the inventory somehow

**Comment by NighthowlerStudios** [comment]
But there's like ten other mods that remove enchantment caps?  are you telling me your mod uses completely new code?

**Comment by hypherionmc** [comment]
Nope. Just thinking of ways to preserve the "vanilla" behavior if needed. 

I take it as the issue here is, that with the full table, you can use books to increase the enchantment level, which is not possible with the portable one, since its not a placeable block

Unless I am understanding the whole thing wrong
